import 'sentence_builder_challenge.dart';

class SentenceBuilderChallenges {
  static const int maxLevel = 10;
  static const int completedSentencesToLevelUp = 2;

  static const List<SentenceBuilderChallenge> all = [
    // NIVEL 1: 2 pictogramas
    SentenceBuilderChallenge(
      id: 'level_1_quiero_agua',
      level: 1,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Quiero agua',
      targetPictogramIds: ['quiero', 'agua'],
      optionPictogramIds: ['quiero', 'agua', 'dormir', 'objeto_pelota'],
    ),
    SentenceBuilderChallenge(
      id: 'level_1_quiero_comer',
      level: 1,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Quiero comer',
      targetPictogramIds: ['quiero', 'comer'],
      optionPictogramIds: ['quiero', 'comer', 'agua', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_1_quiero_dormir',
      level: 1,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Quiero dormir',
      targetPictogramIds: ['quiero', 'dormir'],
      optionPictogramIds: ['quiero', 'dormir', 'comer', 'bebida_agua'],
    ),
    SentenceBuilderChallenge(
      id: 'level_1_quiero_jugar',
      level: 1,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Quiero jugar',
      targetPictogramIds: ['quiero', 'verbo_jugar'],
      optionPictogramIds: ['quiero', 'verbo_jugar', 'dormir', 'comer'],
    ),

    // NIVEL 2: 3 pictogramas
    SentenceBuilderChallenge(
      id: 'level_2_yo_quiero_agua',
      level: 2,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero agua',
      targetPictogramIds: ['yo', 'quiero', 'agua'],
      optionPictogramIds: ['yo', 'quiero', 'agua', 'comer', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_2_yo_quiero_comer',
      level: 2,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero comer',
      targetPictogramIds: ['yo', 'quiero', 'comer'],
      optionPictogramIds: ['yo', 'quiero', 'comer', 'agua', 'objeto_pelota'],
    ),
    SentenceBuilderChallenge(
      id: 'level_2_no_quiero_comer',
      level: 2,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'No quiero comer',
      targetPictogramIds: ['home_no', 'quiero', 'comer'],
      optionPictogramIds: ['home_no', 'quiero', 'comer', 'agua', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_2_quiero_mas_agua',
      level: 2,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Quiero más agua',
      targetPictogramIds: ['quiero', 'tamanos_mas', 'agua'],
      optionPictogramIds: [
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_zumo',
        'tamanos_menos',
      ],
    ),

    // NIVEL 3: 4 pictogramas
    SentenceBuilderChallenge(
      id: 'level_3_yo_quiero_ir_bano',
      level: 3,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero ir al baño',
      targetPictogramIds: ['yo', 'quiero', 'verbo_ir', 'bano'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'bano',
        'lugar_casa',
        'verbo_jugar',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_3_yo_quiero_jugar_pelota',
      level: 3,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero jugar con pelota',
      targetPictogramIds: ['yo', 'quiero', 'verbo_jugar', 'objeto_pelota'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_jugar',
        'objeto_pelota',
        'agua',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_3_no_quiero_dormir_ahora',
      level: 3,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'No quiero dormir ahora',
      targetPictogramIds: ['home_no', 'quiero', 'dormir', 'tiempo_ahora'],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'dormir',
        'tiempo_ahora',
        'tiempo_despues',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_3_yo_quiero_mas_agua',
      level: 3,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero más agua',
      targetPictogramIds: ['yo', 'quiero', 'tamanos_mas', 'agua'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_zumo',
        'bebida_leche',
      ],
    ),

    // NIVEL 4: 5 pictogramas
    SentenceBuilderChallenge(
      id: 'level_4_yo_quiero_ir_al_parque',
      level: 4,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero ir al parque',
      targetPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'lugar_parque',
        'tiempo_ahora',
      ],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'lugar_parque',
        'tiempo_ahora',
        'lugar_casa',
        'lugar_bano',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_4_no_quiero_poner_chaqueta',
      level: 4,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'No quiero poner chaqueta ahora',
      targetPictogramIds: [
        'home_no',
        'quiero',
        'ropa_chaqueta',
        'tiempo_ahora',
      ],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'ropa_chaqueta',
        'tiempo_ahora',
        'ropa_camiseta',
        'ropa_zapatos',
        'dormir',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_4_yo_quiero_escuchar_musica',
      level: 4,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero escuchar música ahora',
      targetPictogramIds: ['yo', 'quiero', 'verbo_escuchar', 'tiempo_ahora'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_escuchar',
        'tiempo_ahora',
        'verbo_jugar',
        'dormir',
        'agua',
        'objeto_tablet',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_4_despues_quiero_ir_casa',
      level: 4,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Después quiero ir a casa',
      targetPictogramIds: [
        'tiempo_despues',
        'quiero',
        'verbo_ir',
        'lugar_casa',
      ],
      optionPictogramIds: [
        'tiempo_despues',
        'quiero',
        'verbo_ir',
        'lugar_casa',
        'lugar_parque',
        'bano',
        'comer',
        'dormir',
      ],
    ),

    // NIVEL 5: frases similares y distractores más parecidos
    SentenceBuilderChallenge(
      id: 'level_5_yo_quiero_mas_agua_fria',
      level: 5,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero más agua fría',
      targetPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_frio',
      ],
      optionPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_frio',
        'bebida_caliente',
        'bebida_zumo',
        'tamanos_menos',
        'comer',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_5_no_quiero_comer_ahora',
      level: 5,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'No quiero comer ahora',
      targetPictogramIds: ['home_no', 'quiero', 'comer', 'tiempo_ahora'],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'comer',
        'tiempo_ahora',
        'tiempo_despues',
        'bebida_agua',
        'bebida_zumo',
        'dormir',
        'tamanos_mas',
        'tamanos_menos',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_5_yo_quiero_ir_bano_ahora',
      level: 5,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Yo quiero ir al baño ahora',
      targetPictogramIds: ['yo', 'quiero', 'verbo_ir', 'bano', 'tiempo_ahora'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'bano',
        'tiempo_ahora',
        'tiempo_despues',
        'lugar_casa',
        'lugar_parque',
        'dormir',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_5_despues_quiero_descansar_cama',
      level: 5,
      mode: SentenceBuilderMode.audioPrompt,
      spokenSentence: 'Después quiero descansar en cama',
      targetPictogramIds: [
        'tiempo_despues',
        'quiero',
        'descansar',
        'casa_cama',
      ],
      optionPictogramIds: [
        'tiempo_despues',
        'quiero',
        'descansar',
        'casa_cama',
        'tiempo_ahora',
        'verbo_jugar',
        'objeto_pelota',
        'lugar_parque',
        'comer',
        'agua',
      ],
    ),
    // NIVEL 6: imagen + frase de 2 pictogramas
    SentenceBuilderChallenge(
      id: 'level_6_image_quiero_agua',
      level: 6,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Quiero agua',
      targetPictogramIds: ['quiero', 'agua'],
      optionPictogramIds: ['quiero', 'agua', 'dormir', 'objeto_pelota'],
    ),
    SentenceBuilderChallenge(
      id: 'level_6_image_quiero_comer',
      level: 6,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Quiero comer',
      targetPictogramIds: ['quiero', 'comer'],
      optionPictogramIds: ['quiero', 'comer', 'agua', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_6_image_quiero_dormir',
      level: 6,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Quiero dormir',
      targetPictogramIds: ['quiero', 'dormir'],
      optionPictogramIds: ['quiero', 'dormir', 'comer', 'agua'],
    ),
    SentenceBuilderChallenge(
      id: 'level_6_image_quiero_jugar',
      level: 6,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Quiero jugar',
      targetPictogramIds: ['quiero', 'verbo_jugar'],
      optionPictogramIds: ['quiero', 'verbo_jugar', 'dormir', 'comer'],
    ),

    // NIVEL 7: imagen + frase de 3 pictogramas
    SentenceBuilderChallenge(
      id: 'level_7_image_yo_quiero_agua',
      level: 7,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero agua',
      targetPictogramIds: ['yo', 'quiero', 'agua'],
      optionPictogramIds: ['yo', 'quiero', 'agua', 'comer', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_7_image_yo_quiero_comer',
      level: 7,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero comer',
      targetPictogramIds: ['yo', 'quiero', 'comer'],
      optionPictogramIds: ['yo', 'quiero', 'comer', 'agua', 'objeto_pelota'],
    ),
    SentenceBuilderChallenge(
      id: 'level_7_image_yo_quiero_jugar',
      level: 7,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero jugar',
      targetPictogramIds: ['yo', 'quiero', 'verbo_jugar'],
      optionPictogramIds: ['yo', 'quiero', 'verbo_jugar', 'comer', 'dormir'],
    ),
    SentenceBuilderChallenge(
      id: 'level_7_image_quiero_mas_agua',
      level: 7,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Quiero más agua',
      targetPictogramIds: ['quiero', 'tamanos_mas', 'agua'],
      optionPictogramIds: [
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_zumo',
        'tamanos_menos',
      ],
    ),

    // NIVEL 8: imagen + frase de 4 pictogramas
    SentenceBuilderChallenge(
      id: 'level_8_image_yo_quiero_ir_bano',
      level: 8,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero ir al baño',
      targetPictogramIds: ['yo', 'quiero', 'verbo_ir', 'bano'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'bano',
        'lugar_casa',
        'verbo_jugar',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_8_image_yo_quiero_jugar_pelota',
      level: 8,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero jugar con pelota',
      targetPictogramIds: ['yo', 'quiero', 'verbo_jugar', 'objeto_pelota'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_jugar',
        'objeto_pelota',
        'agua',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_8_image_no_quiero_dormir_ahora',
      level: 8,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'No quiero dormir ahora',
      targetPictogramIds: ['home_no', 'quiero', 'dormir', 'tiempo_ahora'],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'dormir',
        'tiempo_ahora',
        'tiempo_despues',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_8_image_yo_quiero_mas_agua',
      level: 8,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero más agua',
      targetPictogramIds: ['yo', 'quiero', 'tamanos_mas', 'agua'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_zumo',
        'bebida_leche',
      ],
    ),

    // NIVEL 9: imagen + frase de 4-5 pictogramas
    SentenceBuilderChallenge(
      id: 'level_9_image_yo_quiero_ir_parque',
      level: 9,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero ir al parque ahora',
      targetPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'lugar_parque',
        'tiempo_ahora',
      ],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'lugar_parque',
        'tiempo_ahora',
        'lugar_casa',
        'lugar_bano',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_9_image_despues_quiero_ir_casa',
      level: 9,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Después quiero ir a casa',
      targetPictogramIds: [
        'tiempo_despues',
        'quiero',
        'verbo_ir',
        'lugar_casa',
      ],
      optionPictogramIds: [
        'tiempo_despues',
        'quiero',
        'verbo_ir',
        'lugar_casa',
        'lugar_parque',
        'bano',
        'comer',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_9_image_no_quiero_chaqueta',
      level: 9,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'No quiero chaqueta ahora',
      targetPictogramIds: [
        'home_no',
        'quiero',
        'ropa_chaqueta',
        'tiempo_ahora',
      ],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'ropa_chaqueta',
        'tiempo_ahora',
        'ropa_camiseta',
        'ropa_zapatos',
        'dormir',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_9_image_yo_quiero_escuchar_ahora',
      level: 9,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero escuchar ahora',
      targetPictogramIds: ['yo', 'quiero', 'verbo_escuchar', 'tiempo_ahora'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_escuchar',
        'tiempo_ahora',
        'verbo_jugar',
        'objeto_tablet',
        'agua',
        'dormir',
      ],
    ),

    // NIVEL 10: imagen + distractores parecidos
    SentenceBuilderChallenge(
      id: 'level_10_image_yo_quiero_mas_agua_fria',
      level: 10,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero más agua fría',
      targetPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_frio',
      ],
      optionPictogramIds: [
        'yo',
        'quiero',
        'tamanos_mas',
        'agua',
        'bebida_frio',
        'bebida_caliente',
        'bebida_zumo',
        'tamanos_menos',
        'comer',
        'dormir',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_10_image_yo_quiero_ir_bano_ahora',
      level: 10,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Yo quiero ir al baño ahora',
      targetPictogramIds: ['yo', 'quiero', 'verbo_ir', 'bano', 'tiempo_ahora'],
      optionPictogramIds: [
        'yo',
        'quiero',
        'verbo_ir',
        'bano',
        'tiempo_ahora',
        'tiempo_despues',
        'lugar_casa',
        'lugar_parque',
        'dormir',
        'comer',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_10_image_despues_quiero_descansar_cama',
      level: 10,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'Después quiero descansar en cama',
      targetPictogramIds: [
        'tiempo_despues',
        'quiero',
        'descansar',
        'casa_cama',
      ],
      optionPictogramIds: [
        'tiempo_despues',
        'quiero',
        'descansar',
        'casa_cama',
        'tiempo_ahora',
        'verbo_jugar',
        'objeto_pelota',
        'lugar_parque',
        'comer',
        'agua',
      ],
    ),
    SentenceBuilderChallenge(
      id: 'level_10_image_no_quiero_comer_ahora',
      level: 10,
      mode: SentenceBuilderMode.textPrompt,
      spokenSentence: 'No quiero comer ahora',
      targetPictogramIds: ['home_no', 'quiero', 'comer', 'tiempo_ahora'],
      optionPictogramIds: [
        'home_no',
        'quiero',
        'comer',
        'tiempo_ahora',
        'tiempo_despues',
        'agua',
        'bebida_zumo',
        'dormir',
        'tamanos_mas',
        'tamanos_menos',
      ],
    ),
  ];

  static List<SentenceBuilderChallenge> getByLevel(int level) {
    return all.where((challenge) => challenge.level == level).toList();
  }
}
