// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOziSqz2XqdtzII3B2XHiDTaS7i4PDEig',
    appId: '1:10702788155:web:b1dab8d7d849e4cc9cae1e',
    messagingSenderId: '10702788155',
    projectId: 'comunicador-23052',
    authDomain: 'comunicador-23052.firebaseapp.com',
    storageBucket: 'comunicador-23052.firebasestorage.app',
    measurementId: 'G-1ZKTTXKG5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTV9VF4LyVsw0-ADjM8_8BJnlt2Y1YEXQ',
    appId: '1:10702788155:android:4740943bf764a5629cae1e',
    messagingSenderId: '10702788155',
    projectId: 'comunicador-23052',
    storageBucket: 'comunicador-23052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsj10KlyPw8YK-kcQG7wYs5fJrKb1p5s',
    appId: '1:10702788155:ios:2e7c6c9dd87e5d439cae1e',
    messagingSenderId: '10702788155',
    projectId: 'comunicador-23052',
    storageBucket: 'comunicador-23052.firebasestorage.app',
    iosBundleId: 'com.example.autiComunicator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtsj10KlyPw8YK-kcQG7wYs5fJrKb1p5s',
    appId: '1:10702788155:ios:2e7c6c9dd87e5d439cae1e',
    messagingSenderId: '10702788155',
    projectId: 'comunicador-23052',
    storageBucket: 'comunicador-23052.firebasestorage.app',
    iosBundleId: 'com.example.autiComunicator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOziSqz2XqdtzII3B2XHiDTaS7i4PDEig',
    appId: '1:10702788155:web:3643d7b31232058c9cae1e',
    messagingSenderId: '10702788155',
    projectId: 'comunicador-23052',
    authDomain: 'comunicador-23052.firebaseapp.com',
    storageBucket: 'comunicador-23052.firebasestorage.app',
    measurementId: 'G-4T2V1DH2TE',
  );
}
